version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
      docker: 18
  pre_build:
    commands:
      - echo "Pre_build"
      - echo "Logging in to Amazon ECR"
      - $(aws ecr get-login  --no-include-email --region us-east-1)
  build:
    commands:
      - echo "Build"
      - echo "Entered build phase"
      - echo "Building Java application"
      - cd  medical-representative-schedule-service
      - mvn -DskipTests clean package
      - docker build -t p3-medical-representative-schedule-service:latest .
      - docker tag p3-medical-representative-schedule-service:latest 234825976347.dkr.ecr.us-east-1.amazonaws.com/p3-medical-representative-schedule-service:latest

  post_build:
    commands:
      - echo "Post_build"
      - docker push 234825976347.dkr.ecr.us-east-1.amazonaws.com/p3-medical-representative-schedule-service:latest
      - printf '[{"name":"p3-medical-representative-schedule-service-container","imageUri":"%s"}]' 234825976347.dkr.ecr.us-east-1.amazonaws.com/p3-medical-representative-schedule-service:latest > taskdefinition.json
      - cat taskdefinition.json

artifacts:
  files:
      - medical-representative-schedule-service/taskdefinition.json