# H2 Properties
spring:
  datasource:
    url: jdbc:h2:mem:rpm
    password: root
    username: root
    driver-class-name: org.h2.Driver
    
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  
  h2:
    console:
      enabled: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default

  application:
    name: vendor-service
  
server:
  port: 8003


eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://3.142.148.8:8761/eureka